#!/bin/sh
cd input

STR="%-18s"
INT="%-18d"
printf "$STR$STR$STR$STR\n" " " Original Compressed Ratio
for fil in `ls` ; do
    enc=../tests/$fil.enc
    dec=../tests/$fil.dec

    printf "$STR" "$fil:"`if diff $fil $dec ; then echo "g" ; else echo "b" ; fi`

    # echo -n "ratio: "
    size=`wc -c < $enc`
    # size=`echo "print ($size+7)/8" | python`
    printf "$INT$INT" `wc -c < $fil` `wc -c < $enc`
    echo "$size/`wc -c < $fil`" | bc -l

done
